import turtle
import numpy as np

turtle.shape('turtle')

def F0():
    for i in range(2):
        turtle.forward(40)
        turtle.right(90)
        turtle.forward(80)
        turtle.right(90)
    turtle.penup()
    turtle.forward(80)
    turtle.pendown()

def F1():
    turtle.penup()
    turtle.right(90)
    turtle.forward(40)
    turtle.pendown()
    turtle.left(135)
    turtle.forward(40*2**0.5)
    turtle.right(135)
    turtle.forward(80)
    turtle.backward(80)
    turtle.left(90)
    turtle.penup()
    turtle.forward(40)
    turtle.pendown()

def F2():
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(40)
    turtle.right(45)
    turtle.forward(40*2**0.5)
    turtle.left(135)
    turtle.forward(40)
    turtle.left(90)
    turtle.penup()
    turtle.forward(80)
    turtle.right(90)
    turtle.forward(40)
    turtle.pendown()
def F3():
    turtle.forward(40)
    turtle.right(135)
    turtle.forward(40*2**0.5)
    turtle.left(135)
    turtle.forward(40)
    turtle.right(135)
    turtle.forward(40*2**0.5)
    turtle.left(135)
    turtle.penup()
    turtle.forward(80)
    turtle.left(90)
    turtle.forward(80)
    turtle.right(90)
    turtle.pendown()
def F4():
    turtle.right(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(40)
    turtle.backward(80)
    turtle.right(90)
    turtle.penup()
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(80)
    turtle.right(90)
    turtle.pendown()
def F5():
    turtle.forward(40)
    turtle.backward(40)
    turtle.right(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(40)
    turtle.right(180)
    turtle.penup()
    turtle.forward(80)
    turtle.left(90)
    turtle.forward(80)
    turtle.right(90)
    turtle.pendown()
def F6():
    turtle.penup()
    turtle.forward(40)
    turtle.pendown()
    turtle.right(135)
    turtle.forward(40*2**0.5)
    turtle.left(45)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(40)
    turtle.left(180)
    turtle.penup()
    turtle.forward(80)
    turtle.left(90)
    turtle.forward(40)
    turtle.right(90)
    turtle.pendown()
def F7():
    turtle.forward(40)
    turtle.right(135)
    turtle.forward(40*2**0.5)
    turtle.left(45)
    turtle.forward(40)
    turtle.penup()
    turtle.left(90)
    turtle.forward(80)
    turtle.left(90)
    turtle.forward(80)
    turtle.right(90)
    turtle.pendown()
def F8():
    for i in range(2):
        turtle.forward(40)
        turtle.right(90)
        turtle.forward(80)
        turtle.right(90)
    turtle.right(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(40)
    turtle.penup()
    turtle.right(90)
    turtle.forward(40)
    turtle.pendown()

def F9():
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(40)
    turtle.right(45)
    turtle.forward(40*2**0.5)
    turtle.backward(40*2**0.5)
    turtle.right(45)
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(40)
    turtle.right(90)
    turtle.penup()
    turtle.forward(80)

num = {0:'F0()',1:'F1()',2:'F2()', 3:'F3()', 4:'F4()',5:'F5()',6:'F6()',7:'F7()',8:'F8()',9:'F9()'}
n = map(int, input())
print(n)

for i in n:
    eval(num[i])

turtle.done()
